---
### Deployment for Investment API cluster pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: investment-web
  namespace: {{ .Values.kube.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: container-investment-web
          image: "{{ .Values.docker.namespace }}/{{ .Values.docker.repository }}:web"
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
          - configMapRef:
              name: config-app
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-app
                  key: api-key
            - name: APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-app
                  key: app-password
          volumeMounts:
          - name: shared-logs
            mountPath: /web/logs

      {{- if .Values.kube.logForwarder.enabled }}
        - name: container-forwarder-filebeat
          image: docker.elastic.co/beats/filebeat:8.0.0
          volumeMounts:
          - name: shared-logs
            mountPath: /var/log
          - name: config-filebeat
            mountPath: /usr/share/filebeat/filebeat.yml
            subPath: filebeat.yml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      volumes:
        - name: shared-logs
          emptyDir: {}
        - name: config-filebeat
          configMap:
            name: config-filebeat
      {{- end }}
---

### Service for external traffic to investment API cluster pod
apiVersion: v1
kind: Service
metadata:
  name: investment-web-service-external
  namespace: {{ .Values.kube.namespace }}
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30501
---

### Service for internal traffic to investment API cluster pod
apiVersion: v1
kind: Service
metadata:
  name: investment-web-service-internal
  namespace: {{ .Values.kube.namespace }}
spec:
  type: ClusterIP
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
---