---
apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: {{ .Values.cluster.replicas }}
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
      annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/json.keys_under_root: "false"
        co.elastic.logs/json.add_error_key: "false"
        co.elastic.logs/multiline.pattern: '^\['
        co.elastic.logs/multiline.negate: "true"
        co.elastic.logs/multiline.match: "after"
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          ports:
            - containerPort: 8096
          volumeMounts:
            - name: config
              mountPath: /config
            - name: cache
              mountPath: /cache
            - name: movies
              mountPath: /media/movies
            - name: shows
              mountPath: /media/shows
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-jellyfin-config
        - name: cache
          persistentVolumeClaim:
            claimName: pvc-jellyfin-cache
        - name: movies
          persistentVolumeClaim:
            claimName: pvc-jellyfin-movies
        - name: shows
          persistentVolumeClaim:
            claimName: pvc-jellyfin-shows
