{{- range .Values.storage.volumes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-{{ .name }}
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "{{ .path }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-{{ .name }}
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: manual
  volumeName: pv-jellyfin-{{ .name }}
{{- end }}
