---
### Namespace for the system ###
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.kube.namespace }}
---
### Configuration for Logstash
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-logstash
  namespace: {{ .Values.kube.namespace }}
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      grok {
        match => { "message" => "%{MONTHDAY:day}-%{MONTHNUM:month}-%{YEAR:year} %{TIME:time} \| %{DATA:loggername} \| %{LOGLEVEL:level} \| %{GREEDYDATA:msg}" }
      }

      mutate {
        add_field => { "timestamp" => "%{year}-%{month}-%{day} %{time}" }
        remove_field => ["year", "month", "day", "time"]
      }

      date {
        match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
        target => "@timestamp"
      }

      ## Dynamically Extract First Two Parts of Pod Name as Tag
      if [fields][pod_name] {
        mutate {
          split => { "[fields][pod_name]" => "-" }  # Split pod_name at "-"
        }
        ## Combine the first two parts into a single tag
        if [fields][pod_name][1] {
          mutate {
            add_field => { "pod_role" => "%{[fields][pod_name][0]}-%{[fields][pod_name][1]}" }
          }
        }
      }

      ## Add the extracted pod role as a tag
      if [pod_role] {
        mutate { add_tag => ["%{pod_role}"] }
      }
    }

    
    output {
      stdout { codec => rubydebug }
      {{ .Values.search.engine }} {
        hosts => ["{{ .Values.search.url }}"]
        user => "{{ .Values.logstash.elasticUsername }}"
        password => "{{ .Values.logstash.elasticPassword }}"
        index => "%{[fields][app_name]}"
        ssl => true
        ssl_certificate_verification => false
      }
    }

---
