---
### Deployment for Kibana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.kube.namespace }}
spec:
  replicas: {{ .Values.kube.replicaCount }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.0.0
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://host.docker.internal:9200"
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-es-credentials
                  key: kibana-es-user
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-es-credentials
                  key: kibana-es-password
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"
---

kind: Service
apiVersion: v1
metadata:
  name: kibana-external-service
  namespace: {{ .Values.kube.namespace }}
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601
---