---
### Deployment for Kibana
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Values.kube.namespace }}
spec:
  replicas: {{ .Values.kibana.replica }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          {{- if eq .Values.search.engine "elasticsearch" }}
          image: "docker.elastic.co/kibana/kibana:{{ .Values.kibana.version }}"
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.search.url }}
            - name: ELASTICSEARCH_USERNAME
              value: "{{ .Values.kibana.elasticUsername }}"
            - name: ELASTICSEARCH_PASSWORD
              value: "{{ .Values.kibana.elasticPassword }}"
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"
          {{- else }}
          image: "opensearchproject/opensearch-dashboards:{{ .Values.kibana.version }}"
          ports:
            - containerPort: 5601
          env:
            - name: OPENSEARCH_HOSTS
              value: {{ .Values.search.url }}
            - name: OPENSEARCH_USERNAME
              value: "{{ .Values.kibana.elasticUsername }}"
            - name: OPENSEARCH_PASSWORD
              value: "{{ .Values.kibana.elasticPassword }}"
            - name: OPENSEARCH_SSL_VERIFICATIONMODE
              value: "none"
          {{- end }}
---

kind: Service
apiVersion: v1
metadata:
  name: kibana-external-service
  namespace: {{ .Values.kube.namespace }}
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30601
---