---
### Deployment for Logstash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ .Values.kube.namespace }}
spec:
  replicas: {{ .Values.logstash.replica }}
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          {{- if eq .Values.search.type "elasticsearch" }}
          image: "docker.elastic.co/logstash/logstash:{{ .Values.logstash.version }}"
          {{- else }}
          image: "opensearchproject/logstash-oss-with-opensearch-output-plugin:latest"
          {{- end }}
          ports:
            - containerPort: 5044
          volumeMounts:
            - name: config-logstash
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: config-logstash
          configMap:
            name: config-logstash
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: {{ .Values.kube.namespace }}
spec:
  selector:
    app: logstash
  ports:
    - port: 5044
      targetPort: 5044
---