---
apiVersion: v1
kind: Namespace
metadata:
  name: logging

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: {{ .Values.kibana.replica }}
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
      annotations:
        co.elastic.logs/enabled: "{{ .Values.kibana.logging.enabled }}"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.add_error_key: "true"
    spec:
      containers:
        - name: kibana
          {{- if eq .Values.search.engine "elasticsearch" }}
          image: "docker.elastic.co/kibana/kibana:{{ .Values.kibana.version }}"
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_HOSTS
              value: {{ .Values.search.url }}
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-kibana
                  key: kibana-username
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-kibana
                  key: kibana-password
            - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
              value: "none"
          {{- else }}
          image: "opensearchproject/opensearch-dashboards:{{ .Values.kibana.version }}"
          ports:
            - containerPort: 5601
          env:
            - name: OPENSEARCH_HOSTS
              value: {{ .Values.search.url }}
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-kibana
                  key: kibana-username
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-kibana
                  key: kibana-password
            - name: OPENSEARCH_SSL_VERIFICATIONMODE
              value: "none"
          {{- end }}
---
