---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: logging
spec:
  replicas: {{ .Values.logstash.replica }}
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          {{- if eq .Values.search.engine "elasticsearch" }}
          image: "docker.elastic.co/logstash/logstash:{{ .Values.logstash.version }}"
          {{- else }}
          image: "opensearchproject/logstash-oss-with-opensearch-output-plugin:{{ .Values.logstash.version }}"
          {{- end }}
          ports:
            - containerPort: 5044
          env:
            - name: SEARCH_HOST
              value: {{ .Values.search.url }}
            - name: SEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-logstash
                  key: logstash-username
            - name: SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-logstash
                  key: logstash-password
          volumeMounts:
            - name: config-logstash
              mountPath: /usr/share/logstash/pipeline
      volumes:
        - name: config-logstash
          configMap:
            name: config-logstash
---
