---
kind: Service
apiVersion: v1
metadata:
  name: service-kibana
  namespace: logging
spec:
  selector:
    app: kibana
  type: ClusterIP
  ports:
    - port: 5601
      targetPort: 5601

---
apiVersion: v1
kind: Service
metadata:
  name: service-logstash
  namespace: logging
spec:
  selector:
    app: logstash
  type: ClusterIP
  ports:
    - port: 5044
      targetPort: 5044

---
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-kibana
  namespace: logging
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/service.serversscheme: https
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
{{- range .Values.ingress.hosts }}
        - {{ . }}
{{- end }}
  rules:
{{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-kibana
                port:
                  number: 5601
{{- end }}
{{- end }}
