---
apiVersion: v1
kind: Namespace
metadata:
  name: pipeline

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: pipeline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      annotations:
        co.elastic.logs/enabled: "{{ .Values.logging.enabled }}"
        co.elastic.logs/multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
        co.elastic.logs/multiline.negate: "true"
        co.elastic.logs/multiline.match: "after"
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: pvc-jenkins-home

