---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jenkins-home
spec:
  capacity:
    storage: {{ .Values.storage.volume.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: {{ .Values.storage.volume.path }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-home
  namespace: pipeline
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.volume.size }}
  storageClassName: manual
  volumeName: pv-jenkins-home
