---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.cluster.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torrent-client
  namespace: {{ .Values.cluster.namespace }}
spec:
  replicas: {{ .Values.cluster.replica }}
  selector:
    matchLabels:
      app: torrent-client
  template:
    metadata:
      labels:
        app: torrent-client
    spec:
      containers:
      {{- if .Values.virtual.enabled }}
        - name: vpn
          image: qmcgaw/gluetun:{{ .Values.virtual.version }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
            privileged: false
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "{{ .Values.virtual.provider }}"
            - name: VPN_TYPE
              value: "openvpn"
            - name: OPENVPN_USER
              valueFrom:
                secretKeyRef:
                  name: credentials-vpn
                  key: username
            - name: OPENVPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials-vpn
                  key: password
            - name: SERVER_COUNTRIES
              value: "Japan"
            - name: TZ
              value: "Asia/Kolkata"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
      {{- end }}
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:{{ .Values.torrent.version }}
          env:
            - name: TZ
              value: "Asia/Kolkata"
            - name: WEBUI_PORT
              value: "8080"
          ports:
            - name: webui
              containerPort: 8080
              protocol: TCP
            - name: torrent-tcp
              containerPort: 6881
              protocol: TCP
            - name: torrent-udp
              containerPort: 6881
              protocol: UDP
          volumeMounts:
            - name: qbittorrent-config
              mountPath: /config
            - name: media-storage
              mountPath: /media
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
      
      volumes:
      {{- if .Values.virtual.enabled }}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      {{- end }}
        - name: qbittorrent-config
          emptyDir: {}
        - name: media-storage
          persistentVolumeClaim:
            claimName: pvc-torrent
