---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-torrent
spec:
  storageClassName: manual
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: {{ .Values.torrent.storage.path }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-torrent
  namespace: {{ .Values.cluster.namespace }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.torrent.storage.size }}
  volumeName: pv-torrent
